title:            Hooozer # Site's name
description:      # About your site
url:              # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Hooozer # Your name.

links:
  - name:         Home
    url:          /
  - name:         Feed
    url:          /feed.xml
  # - name:         Email
    # url:          mailto:rezoooh@gmail.com
    # external:     true
  # - name:         GitHub
    # url:          http://github.com/hooozer
    # external:     true
  - name:         About
    url:          /about

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
